import plugin from 'tailwindcss/plugin';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
      extend: {
        colors: {
          primary: {
            DEFAULT: '#0db9f2',
            pink: '#ff007f',
            blue: '#0070ff',
            'pink-light': '#ff4d9a',
            'pink-lighter': '#ff80b5',
            'blue-dark': '#005ccf',
            'blue-light': '#338dff',
            'blue-lighter': '#66aaff',
          },
          pokemon: {
            pink: '#ff007f',
            blue: '#0070ff',
            yellow: '#ffee00',
            gold: '#d4af37',
            green: '#00ff66',
          },
          'neon-pink': '#ff007f',
          'neon-cyan': '#00f3ff',
          'neon-volt': '#ccff00',
          'background-dark': '#0a0705',
          shake: {
            "tertiary-dim": "#874cff",
            "tertiary-fixed-dim": "#b190ff",
            "on-secondary-fixed-variant": "#006666",
            "primary-dim": "#ff51fa",
            "surface-container-low": "#1e0d1e",
            "surface-container-lowest": "#000000",
            "primary-fixed": "#ff5af9",
            "secondary-fixed": "#00fbfb",
            "outline": "#866e81",
            "error-container": "#a70138",
            "on-tertiary-container": "#f8f1ff",
            "tertiary-container": "#7000ff",
            "surface": "#180917",
            "on-primary-container": "#440044",
            "surface-dim": "#180917",
            "primary": "#ff7cf5",
            "on-secondary": "#005c5c",
            "on-primary-fixed-variant": "#540054",
            "surface-container-high": "#2d182c",
            "primary-container": "#ff5af9",
            "background": "#180917",
            "on-primary": "#580058",
            "error": "#ff6e84",
            "secondary-container": "#006a6a",
            "on-background": "#fde0f6",
            "tertiary": "#ac89ff",
            "secondary": "#00fbfb",
            "surface-bright": "#3d233b",
            "on-tertiary-fixed-variant": "#4700a7",
            "on-error": "#490013",
            "secondary-fixed-dim": "#00ecec",
            "surface-container-highest": "#351e33",
            "on-surface": "#fde0f6",
            "inverse-surface": "#fff7fa",
            "primary-fixed-dim": "#ff1cfe",
            "on-secondary-container": "#d9fffe",
            "outline-variant": "#564253",
            "secondary-dim": "#00ecec",
            "inverse-on-surface": "#644f60",
            "tertiary-fixed": "#bda1ff",
            "surface-container": "#261325",
            "surface-tint": "#ff7cf5",
            "error-dim": "#d73357",
            "on-tertiary": "#290067",
            "on-error-container": "#ffb2b9",
            "on-secondary-fixed": "#004747",
            "on-tertiary-fixed": "#1f0052",
            "surface-variant": "#351e33",
            "on-primary-fixed": "#000000",
            "inverse-primary": "#aa00aa",
            "on-surface-variant": "#bda3b8"
          },
        },
        fontSize: {
          'xs': ['0.525rem', { lineHeight: '0.8rem' }],
          'sm': ['0.6125rem', { lineHeight: '1rem' }],
          'base': ['0.7rem', { lineHeight: '1.2rem' }],
          'lg': ['0.7875rem', { lineHeight: '1.3rem' }],
          'xl': ['0.875rem', { lineHeight: '1.4rem' }],
          '2xl': ['1.05rem', { lineHeight: '1.5rem' }],
          '3xl': ['1.3125rem', { lineHeight: '1.7rem' }],
          '4xl': ['1.575rem', { lineHeight: '2rem' }],
          '5xl': ['2.1rem', { lineHeight: '1' }],
          '6xl': ['2.625rem', { lineHeight: '1' }],
          '7xl': ['3.15rem', { lineHeight: '1' }],
          '8xl': ['4.2rem', { lineHeight: '1' }],
          '9xl': ['5.6rem', { lineHeight: '1' }],
        },
        fontFamily: {
          '8-bit': ['"8-bit HUD"', 'sans-serif'],
          poppins: ['Poppins', 'sans-serif'],
          pixel: ['"Press Start 2P"', 'cursive'],
          shake: ["Plus Jakarta Sans", "sans-serif"],
          shakeHeadline: ["Space Grotesk", "sans-serif"],
        },
        animation: {
          'float': 'float 6s ease-in-out infinite',
          'pulse-slow': 'pulse 2s infinite',
          'fade-in-up': 'fadeInUp 0.5s ease-out forwards',
        },
        keyframes: {
          float: {
            '0%, 100%': { transform: 'translateY(0px)' },
            '50%': { transform: 'translateY(-20px)' },
          },
          fadeInUp: {
            '0%': { opacity: '0', transform: 'translateY(20px)' },
            '100%': { opacity: '1', transform: 'translateY(0)' },
          },
        },
        backdropBlur: {
          xs: '2px',
        },
      },
    },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        '.perspective-1000': {
          perspective: '1000px',
        },
        '.transform-style-3d': {
          'transform-style': 'preserve-3d',
        },
        '.backface-hidden': {
          'backface-visibility': 'hidden',
        },
        '.rotate-y-180': {
          transform: 'rotateY(180deg)',
        },
      });
    }),
  ],
}