export const musicData = [
    {
        id: 1,
        title: "Love Cat「愛猫」",
        artist: "biz×ZERA",
        coverArtist: "COVER【Shura Hiwa】",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1771718211/Love_Cat_%E6%84%9B%E7%8C%AB_-_biz_ZERA_COVER_Shura_Hiwa_moroj3.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-MSEwN92aqPw-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/Love%20Cat%E3%80%8C%E6%84%9B%E7%8C%AB%E3%80%8D-%20%20biz%C3%97ZERA%20%20COVER%E3%80%90Shura%20Hiwa%E3%80%91.mp4",
        lyrics: [
            { time: "0:00", text: "作詞・作曲・編曲 初音ミクおかりなさい君に似合う" },
            { time: "0:30", text: "悪い子ね 汚れても" },
            { time: "0:33", text: "君が眩しく感じるのは" },
            { time: "0:37", text: "愛は知らない明日にこそ" },
            { time: "0:41", text: "間抜けの愛嬌とか" },
            { time: "0:45", text: "そりゃ結構 ヘラメカ" },
            { time: "0:48", text: "ネバネバネで妄想" },
            { time: "0:51", text: "目をしおきだ自己嫌悪" },
            { time: "0:54", text: "君は私だけの愛猫だよ" },
            { time: "0:58", text: "どんどん好きになる" },
            { time: "1:02", text: "明日" },
            { time: "1:03", text: "どんどん好きになる明日どんどん" },
            { time: "1:05", text: "好きになる" },
            { time: "1:07", text: "明日" },
            { time: "1:09", text: "可愛いね 首輪つけてにゃお" },
            { time: "1:12", text: "大切にめでてあげるにゃお" },
            { time: "1:16", text: "俺の中の子猫ちゃん" },
            { time: "1:19", text: "愛の文章をさあ踊りましょう" },
            { time: "1:23", text: "喉の脱脂するようで ほらどうぞ" },
            { time: "1:28", text: "ペラメッコ あら 甘えんぼさん" },
            { time: "1:31", text: "そっと向いても そりゃ結構" },
            { time: "1:35", text: "君は私だけの愛猫だ" },
            { time: "1:39", text: "トントン 好きになる" },
            { time: "1:43", text: "明日" },
            { time: "1:44", text: "トントン 好きになる明日どんどん" },
            { time: "1:45", text: "好きになる" },
            { time: "1:47", text: "明日" },
            { time: "1:49", text: "逃げられやしないのばっかね" },
            { time: "1:52", text: "無性の愛が欲しいのを愛して" },
            { time: "1:55", text: "楽しいのだって君は" },
            { time: "1:57", text: "いいねこーさんご視聴ありがとうございました" },
        ]
    },
    {
        id: 2,
        title: "Ambivalent (アンビバレント)",
        artist: "Uru",
        coverArtist: "Shura Hiwa (3D COVER)",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1767940765/%E3%82%A2%E3%83%B3%E3%83%93%E3%83%90%E3%83%AC%E3%83%B3%E3%83%88_Ambivalent_-_Uru_3D_COVER_Shura_Hiwa_nk0ii1.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-6ofpBhCvB5U-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/%E3%80%8C%E3%82%A2%E3%83%B3%E3%83%93%E3%83%90%E3%83%AC%E3%83%B3%E3%83%88%E3%80%8D(ambivalent)_-_uru__3d_cover%E3%80%90shura_hiwa%E3%80%91_v1%20(1080p).mp4",
        lyrics: [
            { time: "0:00", text: "作詞・作曲・編曲 初音ミクいつだって君は恐れを知らず" },
            { time: "0:28", text: "好きなものに夢中な猫みたいで" },
            { time: "0:35", text: "君が眩しく感じるのは" },
            { time: "0:40", text: "きっと僕が君を見てたから" },
            { time: "0:43", text: "刺激的な思考回路" },
            { time: "0:48", text: "惹かれてく" },
            { time: "0:51", text: "青い青いその瞳に" },
            { time: "0:59", text: "僕はまだ映らない" },
            { time: "1:02", text: "君は今日もいつもの" },
            { time: "1:05", text: "君のまま" },
            { time: "1:08", text: "揺れる揺れる" },
            { time: "1:11", text: "この気持ちは" },
            { time: "1:13", text: "どこかにしまったまま" },
            { time: "1:17", text: "今はここでただ横顔を見てるOh oh oh oh oh oh" },
            { time: "1:36", text: "酸いも甘いも知ってるフリをして肩にはまった" },
            { time: "1:47", text: "窮屈な日々の中" },
            { time: "1:51", text: "見慣れていたこの" },
            { time: "1:53", text: "かしめきに" },
            { time: "1:54", text: "新しい風が" },
            { time: "1:56", text: "吹き込んだような" },
            { time: "1:58", text: "刺激的な" },
            { time: "2:00", text: "その存在" },
            { time: "2:04", text: "惹かれてく" },
            { time: "2:08", text: "僕をまだ映さない" },
            { time: "2:12", text: "こんなにもすぐそばにいるけれど" },
            { time: "2:16", text: "混ざり合わない" },
            { time: "2:23", text: "二人の距離" },
            { time: "2:25", text: "いたものは僕だけ" },
            { time: "2:27", text: "今はここで" },
            { time: "2:30", text: "ただ横顔を見てる" },
            { time: "2:33", text: "何かに" },
            { time: "2:37", text: "つまずいた" },
            { time: "2:39", text: "時には" },
            { time: "2:41", text: "君ならどうするかな" },
            { time: "2:47", text: "なんで思ったり" },
            { time: "2:50", text: "もう少しやってみようなんてさ" },
            { time: "2:56", text: "思えたりするんだよ" },
            { time: "3:00", text: "おかしいね" },
            { time: "3:02", text: "僕は気づいてる" },
            { time: "3:05", text: "青い青いその瞳に 僕は映らないけど" },
            { time: "3:25", text: "君はいつも笑っていて欲しい" },
            { time: "3:32", text: "好きなことにときめいていて" },
            { time: "3:37", text: "そう僕はいつだって" },
            { time: "3:41", text: "きっとそのままの君が好きなんだ" },
        ]
    },
    {
        id: 3,
        title: "Bunny Girl (バニーガール)",
        artist: "AKASAKI",
        coverArtist: "Shura Hiwa (COVER ESPAÑOL)",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1767943023/BUNNY_GIRL_-_AKASAKI_COVER_ESPA%C3%91OL_Shura_Hiwa_ppkf51.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-5iY0fGEl4JE-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/bunny_girl_-_akasaki__cover_espa%C3%91ol%E3%80%90shura_hiwa%E3%80%91_v1%20(1080p).mp4",
        lyrics: [
            { time: "0:00", text: "La noche apenas va a empezar" },
            { time: "0:02", text: "Bunny Girl" },
            { time: "0:04", text: "Mi corazón vas a seducir" },
            { time: "0:07", text: "Brindemos juntos por" },
            { time: "0:09", text: "El amor que falta." },
            { time: "0:11", text: "Y puede que lo notes" },
            { time: "0:12", text: "O no" },
            { time: "0:13", text: "Aquí el romance va a empezar" },
            { time: "0:15", text: "Bunny Girl" },
            { time: "0:16", text: "En ti me quiero PERDER" },
            { time: "0:19", text: "Pues tú lo logras solo con" },
            { time: "0:22", text: "MIRARME." },
            { time: "0:23", text: "🎵" },
            { time: "0:35", text: "Ya, quita las penas y acércate" },
            { time: "0:39", text: "Sé que el trabajo te puede cansar..." },
            { time: "0:42", text: "así que ven y déjamelo a mí." },
            { time: "0:47", text: "Ya, déjalo todo ir relájate." },
            { time: "0:51", text: "Todo lo malo que tú puedes sentir." },
            { time: "0:54", text: "¿Sería yo en quién lo puedes confiar?" },
            { time: "0:58", text: "Aunque sea solo una canción de AMOR" },
            { time: "1:01", text: "El sentimiento es abrumador" },
            { time: "1:04", text: "Y aún si tú no me lo dejas ver" },
            { time: "1:07", text: "Siento que en tu mirada hay dolor." },
            { time: "1:10", text: "Si no lo quieres no te forzaré," },
            { time: "1:13", text: "Pero yo siempre te voy a escuchar." },
            { time: "1:16", text: "Vamos a olvidarlo todo, ya verás que yo no te voy a..." },
            { time: "1:21", text: "SOLTAR" },
            { time: "1:22", text: "La noche apenas va a empezar" },
            { time: "1:23", text: "Bunny Girl" },
            { time: "1:25", text: "Mi corazón vas a seducir" },
            { time: "1:28", text: "Brindemos juntos por" },
            { time: "1:30", text: "El amor que falta." },
            { time: "1:32", text: "Y puede que lo notes" },
            { time: "1:33", text: "O no" },
            { time: "1:34", text: "Aquí el romance va a empezar" },
            { time: "1:36", text: "Bunny Girl" },
            { time: "1:37", text: "En ti me quiero PERDER" },
            { time: "1:40", text: "Pues tú lo logras solo con" },
            { time: "1:43", text: "MIRARME." },
            { time: "1:44", text: "🎵" },
            { time: "1:56", text: "Todo tu amor me quita el pesar." },
            { time: "1:58", text: "Y aunque ocultarlo trate..." },
            { time: "2:00", text: "Solamente me siento a llorar." },
            { time: "2:03", text: "Porque esto es lo que quieres...¿o no?" },
            { time: "2:08", text: "Ya, quita las penas y acércate" },
            { time: "2:12", text: "Veo que de poco a poco mejorarás" },
            { time: "2:15", text: "Porque tu rostro comienza a cambiar" },
            { time: "2:17", text: "🎵" },
            { time: "2:41", text: "Ahora en ti voy a confiar..." },
            { time: "2:43", text: "Bunny Girl" },
            { time: "2:44", text: "A ti yo me voy a entregar" },
            { time: "2:46", text: "Bunny Girl" },
            { time: "2:47", text: "Mi corazón vas a seducir" },
            { time: "2:50", text: "Brindemos juntos por" },
            { time: "2:52", text: "El amor que falta." },
            { time: "2:54", text: "Aún si aquí estamos TODOS" },
            { time: "2:56", text: "La noche apenas va a empezar" },
            { time: "2:58", text: "Bunny Girl" },
            { time: "2:59", text: "En ti me quiero PERDER" },
            { time: "3:02", text: "Pues tú lo logras solo con" },
            { time: "3:05", text: "MIRARME." },
        ]
    },
    {
        id: 4,
        title: "ワールドイズマイン」(World is Mine)",
        artist: "Ryo",
        coverArtist: "Shura Hiwa (COVER)",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1768189197/%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%82%A4%E3%82%BA%E3%83%9E%E3%82%A4%E3%83%B3_World_is_Mine_-_Drums_Voice_ver._-_COVER_Shura_Hiwa_jb7dak.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-1rsO4oJH8gs-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/%E3%80%8C%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%82%A4%E3%82%BA%E3%83%9E%E3%82%A4%E3%83%B3%E3%80%8D(world_is_mine)_-_drums_%26_voice_ver._-___cover%E3%80%90shura_hiwa%E3%80%91_v1%20(1080p).mp4",
        lyrics: [
            { time: "0:00", text: "世界で一番の姫様" },
            { time: "0:06", text: "そういう扱い心得てよねその1 いつもと違う髪型に気が付くこと" },
            { time: "0:35", text: "その2 ちゃんと靴まで見ることいいね" },
            { time: "0:40", text: "その3 私の人には3つの言葉で" },
            { time: "0:45", text: "チェンジすること" },
            { time: "0:47", text: "分かれたら" },
            { time: "0:49", text: "握ってガールスなの" },
            { time: "0:51", text: "何とかして" },
            { time: "0:52", text: "別に" },
            { time: "0:54", text: "わがままなんて" },
            { time: "0:56", text: "言ってないんだから" },
            { time: "0:58", text: "君に" },
            { time: "1:00", text: "心から思って" },
            { time: "1:04", text: "欲しいのかわいいって" },
            { time: "1:06", text: "世界で一番の姫様に気がついて" },
            { time: "1:14", text: "ねえねえ待たせるなんて論外よ" },
            { time: "1:18", text: "私を慣れそう思ってるのお腹が空いてるの?もう何だか" },
            { time: "1:26", text: "甘いものが食べたい" },
            { time: "1:30", text: "今すぐによ" },
            { time: "1:43", text: "ケテン" },
            { time: "1:44", text: "可愛いの間違いでしょ" },
            { time: "1:46", text: "もっとは許しませんの" },
            { time: "1:49", text: "あのね私の話ちゃんと聞いてる" },
            { time: "1:54", text: "ちょっと" },
            { time: "1:54", text: "あそれとね" },
            { time: "1:56", text: "白い馬さん決まってるでしょ" },
            { time: "1:59", text: "迎えに来てわかったら" },
            { time: "2:03", text: "差しついて手を取って お姫様って" },
            { time: "2:07", text: "別にわがままなんて 言ってないんだから" },
            { time: "2:13", text: "でもね 少しぐらい 誓ってくれたっていいのよ" },
            { time: "2:20", text: "世界で私だけの王子様" },
            { time: "2:26", text: "近づいて ほらほら" },
            { time: "2:29", text: "おててが空いてます" },
            { time: "2:32", text: "無口で不愛想な王子様" },
            { time: "2:37", text: "もうどうして" },
            { time: "2:41", text: "気がついてよ早く正解君は分かってない" },
            { time: "2:52", text: "分かってないわ" },
            { time: "2:56", text: "いちご布だショートケーキ" },
            { time: "3:04", text: "こだわり卵のとろけるプリン" },
            { time: "3:07", text: "みんなみんな我慢します" },
            { time: "3:10", text: "わがままな子だと思わないで" },
            { time: "3:13", text: "私だってやればできるもん" },
            { time: "3:16", text: "あとで効果するわよ" },
            { time: "3:19", text: "挑戦ですだだけ私は世界で一番の姫様" },
            { time: "3:29", text: "ちゃんと見ててよね" },
            { time: "3:33", text: "どこかに行っちゃうよ" },
            { time: "3:36", text: "不意に抱きしめられた" },
            { time: "3:39", text: "急にそんなに" },
            { time: "3:41", text: "控える危ないよ" },
            { time: "3:45", text: "そう言って トップもグッビーに" },
            { time: "3:48", text: "どっちの顔 ないわよAh..." }
        ]
    },
    {
        id: 5,
        title: "Poppinparty Remix",
        artist: "Romeo and Cinderella",
        coverArtist: "COVER ESPAÑOL【Shura Hiwa】",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1768668808/Romeo_and_Cinderella_-%E1%B4%98%E1%B4%8F%E1%B4%98%E1%B4%98%C9%AA%C9%B4%E1%B4%98%E1%B4%80%CA%80%E1%B4%9B%CA%8F_%CA%80%E1%B4%87%E1%B4%8D%C9%AAx-_COVER_ESPA%C3%91OL_Shura_Hiwa_nhknmh.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-qFsd75mLpgQ-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/%E3%80%8Cromeo_and_cinderella%E3%80%8D-%E1%B4%98%E1%B4%8F%E1%B4%98%E1%B4%98%C9%AA%C9%B4%E1%B4%98%E1%B4%80%CA%80%E1%B4%9B%CA%8F_%CA%80%E1%B4%87%E1%B4%8D%C9%AAx-___cover_espa%C3%91ol%E3%80%90shura_hiwa%E3%80%91_v1%20(1080p).mp4",
        lyrics: [
            { time: "0:00", text: "No permites que este amor se convierta en la tragedia de Julita" },
            { time: "0:07", text: "Quiero escapar de aquí contigo con este sentimiento" },
            { time: "0:13", text: "Papá y mamá ya es muy tarde, buenas noches" },
            { time: "0:27", text: "Espero que disfruten de muy dulces sueños" },
            { time: "0:30", text: "Es hora de que los adultos duerman ya" },
            { time: "0:34", text: "Los labios saben el más dulce caramelo" },
            { time: "0:38", text: "Suspiro al cruzar las piernas con recelo" },
            { time: "0:41", text: "Quiero saber a dónde iremos esta vez?" },
            { time: "0:46", text: "Por favor ya no me muerdas, soy gentil conmigo" },
            { time: "0:49", text: "No me he acostumbrado a lo amargo aún" },
            { time: "0:52", text: "Quizá fue por los dulces y pasteles que mi madre preparó" },
            { time: "0:56", text: "Esta sensación tan fuerte y tan desconocida" },
            { time: "1:00", text: "Yo no comprendía lo que iba a pasar" },
            { time: "1:03", text: "Ya no me escondas nada porque yo solo a ti" },
            { time: "1:06", text: "Te mostraré lo que hay en mí" },
            { time: "1:09", text: "Yo quiero ser como Zenith en T-Soyal" },
            { time: "1:13", text: "Voy a escapar tan solo con mi uniforme" },
            { time: "1:16", text: "La magia el tiempo va a poder detener" },
            { time: "1:18", text: "Antes de que la bruja mala nos encuentre" },
            { time: "1:22", text: "Yo quiero escapar como juelita" },
            { time: "1:24", text: "Pero por ese nombre no vas a llamarme" },
            { time: "1:27", text: "Nuestras vidas juntas siempre estarán o volverán a ser demasiado aburridas" },
            { time: "1:33", text: "Contigo yo quiero pasar la eternidad" },
            { time: "1:50", text: "El maquillaje me ha vuelto llamativa" },
            { time: "1:53", text: "Prometo ser mañana una buena niña" },
            { time: "1:56", text: "Perdóname, solo por esta ocasión" },
            { time: "2:00", text: "Al inentro el encaje negro y el pecado" },
            { time: "2:04", text: "Nada ni nadie el día de hoy lo ha asegurado" },
            { time: "2:07", text: "Quiero saber a dónde iremos esta vez" },
            { time: "2:12", text: "Te pido perdón si muerdo, si te lastimo" },
            { time: "2:15", text: "Pero te confieso, siento tanto amor" },
            { time: "2:18", text: "Aunque al parecer mi padre ya te odia sin una razón" },
            { time: "2:22", text: "Recuerdo que me diraste un regalo a Zaste" },
            { time: "2:26", text: "Y en ese instante te di mi corazón" },
            { time: "2:29", text: "Romeo, escapemos tan lejos que jamás" },
            { time: "2:32", text: "Nadie nos llegue a encontrar" },
            { time: "2:36", text: "Como cenicienta ahora debes acabar" },
            { time: "2:39", text: "Dejé mi zapatilla de cristal tirada" },
            { time: "2:42", text: "Y esperaré a que llegues pronto a mí" },
            { time: "2:44", text: "Antes de que estás de nada Te esperaré a que llegues pronto a mí Antes de que estés en mi cuarto" },
            { time: "2:46", text: "Es una pesadilla, seguro que ella también lo hizo así" },
            { time: "2:50", text: "Mientras le cerca la dejo por así de entre" },
            { time: "2:53", text: "Cuando él me encuentre mentiras diré" },
            { time: "2:56", text: "Yo voy a ser la chica de la que se enamore" },
            { time: "2:59", text: "Ahora solo date cuenta que aquí estoy" },
            { time: "3:17", text: "No quieres saber qué dice el corazón que a ti te entrego" },
            { time: "3:22", text: "Está lleno de deseo" },
            { time: "3:25", text: "Tú lo provocas" },
            { time: "3:26", text: "Estás muy serio" },
            { time: "3:28", text: "Ahora no es suficiente" },
            { time: "3:30", text: "Lo quiero todo" },
            { time: "3:32", text: "He sido paciente" },
            { time: "3:34", text: "Tan llena toda mi vida" },
            { time: "3:36", text: "Que tu pasión ahora es mi salida" },
            { time: "3:38", text: "Sin ti yo no podría ser feliz" },
            { time: "3:44", text: "Aquel sentimiento que yo siempre busqué" },
            { time: "3:47", text: "Lo encontré al abrir la caja de Pandora" },
            { time: "3:50", text: "¿Qué debo hacer? ¿Qué es lo correcto esta vez?" },
            { time: "3:52", text: "Quedarme junto a ti" },
            { time: "3:54", text: "¿O debo abandonarte?" },
            { time: "3:55", text: "No me puedo entender por qué mamá y papá" },
            { time: "3:58", text: "No pueden ver que el amor me hizo ya distinta" },
            { time: "4:01", text: "Lo único que estoy dispuesta a perder" },
            { time: "4:04", text: "Aquella cha de oro Quien era mía Luego de mentir tanto como ya distinta Lo único que estoy dispuesta a perder Aquella hecha devoró" },
            { time: "4:05", text: "Quindera mía" },
            { time: "4:07", text: "Luego de mentir tanto como se distinta" },
            { time: "4:09", text: "Ya dice que seré comida por el lobo" },
            { time: "4:12", text: "¿Qué debo hacer?" },
            { time: "4:14", text: "¿Qué es lo correcto esta vez?" },
            { time: "4:15", text: "¿O seré devorada por él sin quererlo?" },
            { time: "4:18", text: "Hoy te pido de mí" },
            { time: "4:20", text: "Y pronto tú por mí" },
        ]
    },
    {
        id: 6,
        title: "「強風オールバック」(Kyoufuu All Back) - Band Arrange ver.",
        artist: "Yukopi_",
        coverArtist: "COVER【Shura Hiwa】",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1768785075/%E5%BC%B7%E9%A2%A8%E3%82%AA%E3%83%BC%E3%83%AB%E3%83%90%E3%83%83%E3%82%AF_Kyoufuu_All_Back_-_Band_Arrange_ver._-_COVER_Shura_Hiwa_uwoblw.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-f63KlhLjpk8-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/%E3%80%8C%E5%BC%B7%E9%A2%A8%E3%82%AA%E3%83%BC%E3%83%AB%E3%83%90%E3%83%83%E3%82%AF%E3%80%8D(kyoufuu_all_back)_-_band_arrange_ver._-__cover%E3%80%90shura_hiwa%E3%80%91_v1%20(1080p).mp4",
        lyrics: [
            { time: "0:00", text: "こんにちは!" },
            { time: "0:02", text: "シャキガングでどうやってブレイクイッダウン" },
            { time: "0:04", text: "それから教えてあげるよ!" },
            { time: "0:06", text: "はい、レディ、ヒューイゴー!" },
            { time: "0:07", text: "そっと出た瞬間 オラタは" },
            { time: "0:11", text: "元気はいいのに進めない" },
            { time: "0:14", text: "カッセ!強すぎてお亡くなり" },
            { time: "0:18", text: "てきてきてきにオールバックAll the way back hereラタタラタタラタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタタララタララタララタララ" },
            { time: "0:35", text: "地下に潜りたいなって思いました風さえなくなれば" },
            { time: "0:46", text: "あったかいのに" },
            { time: "0:49", text: "ずっと座りたいな" },
            { time: "0:53", text: "って思いました" },
            { time: "0:56", text: "イヤイヤと外れたら" },
            { time: "1:00", text: "ハトハトハトハト大乱闘" },
            { time: "1:03", text: "外れた瞬間終わった" },
            { time: "1:07", text: "敵はいいのに進めない" },
            { time: "1:11", text: "覚醒強すぎてお亡くなり" },
            { time: "1:15", text: "敵敵敵にオールバックOh oh oh oh oh oh oh oh oh oh oh oh oh oh oh 3rd grade in the back with a slap backI got crack open and stack backNo lunch, got a finger and I kick ass" },
            { time: "1:45", text: "Feet are scattered when there's one in the back pack" },
            { time: "1:47", text: "Street fighter too with a roll back" },
            { time: "1:49", text: "No, I'm not that old, it's a throwback" },
            { time: "1:50", text: "When I lift, don't ease but I hold back" },
            { time: "1:52", text: "Hookin' on the streets, no cap with the hair blowin' all back" },
            { time: "1:54", text: "外出た瞬間 終わったわ" },
            { time: "1:58", text: "天気はいいのに進めないが" },
            { time: "2:01", text: "背強すぎてもう無くなり敵 敵 敵にオールバック" },
            { time: "2:08", text: "髪の毛恐怖オールバックチャンネル登録よろしくお願いします" },
        ]
    },
    {
        id: 7,
        title: "ENVY BABY",
        artist: "KANARIA",
        coverArtist: "COVER【Shura Hiwa】",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1769229866/ENVY_BABY_-_KANARIA_COVER_Shura_Hiwa_s5vq7a.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-poZj51z9u7k-maxresdefault.jpg",
        backgroundVideo: "https://pub-ed644fbc43ed4c4788d9c013963a7b8e.r2.dev/envy_baby_-_kanaria__cover%E3%80%90shura_hiwa%E3%80%91_v1%20(1080p).mp4",
        lyrics: [
            { time: "0:01", text: "Hi All right?" },
            { time: "0:03", text: "I wanna be people save." },
            { time: "0:04", text: "Alright" },
            { time: "0:06", text: "Ma-ma-ma-ma-ma-ma-ma-ma..." },
            { time: "0:07", text: "Envy baby." },
            { time: "0:09", text: "Envy baby." },
            { time: "0:11", text: "Envy baby." },
            { time: "0:13", text: "Envy baby." },
            { time: "0:15", text: "Envy baby." },
            { time: "0:18", text: "Saiteiroku wa kuzureru kowasareru donna reidi." },
            { time: "0:24", text: "Naito mekakete buzama ni kudakareru sonna shourai." },
            { time: "0:29", text: "Ainiki mama ni lonely, lonely." },
            { time: "0:32", text: "Aita kotoba de rolly, rolly." },
            { time: "0:35", text: "Aimokawarazu koukai?" },
            { time: "0:40", text: "I’m ready!" },
            { time: "0:40", text: "This, this lover baby." },
            { time: "0:42", text: "Ai no sono semari kuru fukute ni." },
            { time: "0:46", text: "Masani this, this lover crazy." },
            { time: "0:50", text: "Dainosoro hito no me wa rai-ai-ai-ai..." },
            { time: "0:52", text: "Ah, aishiteru!" },
            { time: "0:53", text: "Sugita koto made suki suki." },
            { time: "0:56", text: "Hitotsu futatsu de lie, lie, loving you." },
            { time: "1:00", text: "Sonna kotoba de, sonna koto made..." },
            { time: "1:01", text: "Ma-ma-ma-ma-ma-ma-ma-ma..." },
            { time: "1:03", text: "Envy baby." },
            { time: "1:06", text: "Envy baby." },
            { time: "1:08", text: "Envy baby." },
            { time: "1:11", text: "Envy baby." },
            { time: "1:14", text: "Gutto rai-rai-rabu maniaberu." },
            { time: "1:17", text: "Binbou nakigoto kasanete." },
            { time: "1:20", text: "Hai hai koise yo yai-yai." },
            { time: "1:23", text: "Ibanete kawa kutte shite." },
            { time: "1:25", text: "Mitsu kasanete lonely, lonely." },
            { time: "1:28", text: "Kitto anata wa lonely, lonely." },
            { time: "1:31", text: "Aimokawarazu koukai?" },
            { time: "1:34", text: "Hey, it's amazing!" },
            { time: "1:36", text: "I’m ready!" },
            { time: "1:37", text: "This, this lover baby." },
            { time: "1:38", text: "Ai no sono semari kuru fukute ni." },
            { time: "1:41", text: "Masani this, this lover crazy." },
            { time: "1:44", text: "Dainosoro hito no me wa rai-ai-ai-ai..." },
            { time: "1:48", text: "Ah, aishiteru!" },
            { time: "1:49", text: "Sugita koto made suki suki." },
            { time: "1:52", text: "Hitotsu futatsu de lie, lie, loving you." },
            { time: "1:55", text: "Sonna kotoba de, sonna koto made..." },
            { time: "1:58", text: "Ma-ma-ma-ma-ma-ma-ma-ma..." },
            { time: "1:59", text: "This, this lover baby." },
            { time: "2:04", text: "This, this lover baby." },
        ]
    },
    {
        id: 8,
        title: "アニマル (Animal)",
        artist: "DECO*27",
        coverArtist: "COVER【Shura Hiwa】",
        audioUrl: "https://res.cloudinary.com/dlpzdoznd/video/upload/v1773848604/%E3%82%A2%E3%83%8B%E3%83%9E%E3%83%AB_Animal_-_DECO27_COVERShura_Hiwa.mp3",
        coverUrl: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/miniatura-youtube-iqdG5qNO1_4-maxresdefault.jpg",
        backgroundVideo: "https://pub-bdbaaa8e6a3e405c965b621a6503229c.r2.dev/%E3%80%8C%E3%82%A2%E3%83%8B%E3%83%9E%E3%83%AB%E3%80%8D(Animal)%20-%20DECO27%20%20COVER%E3%80%90Shura%20Hiwa%E3%80%91%20-%20Shura%20Hiwa%20Ch..mp4",
        lyrics: [
            { time: "0:00", text: "剥がれ落ちたメイク" },
            { time: "0:02", text: "すっぴーのアニマル" },
            { time: "0:04", text: "目ぬぐくてもやっちゃうのよ" },
            { time: "0:06", text: "おすわりとかできない" },
            { time: "0:07", text: "だって負けもできない" },
            { time: "0:09", text: "ロボ鳴らして言っちゃうまで" },
            { time: "0:11", text: "どっちしようか高まるビート" },
            { time: "0:24", text: "良いも悪いも宣伝しよう" },
            { time: "0:26", text: "ハマってみようか突破するゲート" },
            { time: "0:29", text: "愛に期待は禁物だよ" },
            { time: "0:31", text: "ねえ止まれないほどに狂いたい" },
            { time: "0:34", text: "心真っ赤にしてどうしちゃったの" },
            { time: "0:36", text: "たのしれもし愛せたら" },
            { time: "0:39", text: "私は幸せです" },
            { time: "0:41", text: "剥がれ落ちたメイク" },
            { time: "0:43", text: "すっぴーのアニマル" },
            { time: "0:44", text: "目ぬぐくてもやっちゃうのよ" },
            { time: "0:47", text: "おすわりとかできない" },
            { time: "0:48", text: "だって負けもできない" },
            { time: "0:50", text: "ロボ鳴らして言っちゃうまで" },
            { time: "0:52", text: "牙を出し叫ぶ" },
            { time: "0:53", text: "すっぴーのアニマル" },
            { time: "0:54", text: "私は噛みついたら離さない" },
            { time: "0:57", text: "剥がれ落ちたメイク" },
            { time: "0:58", text: "すっぴーのアニマル" },
            { time: "1:00", text: "目ぬぐくてもやっちゃうのよ" },
            { time: "1:04", text: "当たっちゃったよ" },
            { time: "1:06", text: "狂っちゃったよ" },
            { time: "1:07", text: "濁っちゃったよ" },
            { time: "1:08", text: "ウワッハッハッハ" },
            { time: "1:10", text: "当たっちゃったよ" },
            { time: "1:11", text: "狂っちゃったよ" },
            { time: "1:12", text: " 濁っちゃったよ" },
            { time: "1:13", text: "ウワッハッハッハッハ" },
            { time: "1:17", text: "プライガンなくてつまんない" },
            { time: "1:20", text: "せめてちょっと拒んでほしかったな" },
            { time: "1:22", text: "少しだけ役割のなら" },
            { time: "1:25", text: "私は幸せになりたいです" },
            { time: "1:39", text: "剥がれ落ちたメイク" },
            { time: "1:40", text: "すっぴーのアニマル" },
            { time: "1:42", text: "目ぬぐくてもやっちゃうのよ" },
            { time: "1:44", text: "おすわりとかできない" },
            { time: "1:45", text: "だって負けもできない" },
            { time: "1:47", text: "ロボ鳴らして言っちゃうまで" },
            { time: "1:49", text: "溶かされたメイク" },
            { time: "1:51", text: "だっちりなアニマル" },
            { time: "1:52", text: "目を開いて待ってるのよ" },
            { time: "1:54", text: "おすわりとかできない" },
            { time: "1:56", text: "だって負けもできない" },
            { time: "1:57", text: "ロボ鳴らして言っちゃうまで" },
            { time: "1:59", text: "牙を出し叫びを呟く" },
            { time: "2:01", text: "さあ私はやめついたら離さない" },
            { time: "2:04", text: "溶かされたメイク" },
            { time: "2:06", text: "だっちりなアニマル" },
            { time: "2:07", text: "目を開いて待ってるのよ" },
        ]
    }
];
